/**
 * The values that fill the RCPS (상환전환우선주) investment agreement, and the
 * tokens each one lands in.
 *
 * The template (templates/rcps-agreement.docx) was tokenised by a verified
 * cursor scan: each {{rN}} was placed at a placeholder anchored by its unique
 * preceding label, and every token was confirmed to occur exactly once unless
 * the field's `tokens` array lists more than one ID.
 *
 * Draft — the mentor should review the first generated RCPS .docx before it is
 * used for a real deal. Standard terms (배당 1%, 연복리 12%, 잔여재산 7%, IPO/M&A
 * 70%, 상환 2년, 퇴사제한 4년 등) are pre-filled with SparkLabs defaults and
 * flagged if changed.
 */

import type { AgreementGroup } from "./agreement-fields";

export const RCPS_GROUPS: AgreementGroup[] = [
  {
    id: "rcps-dates",
    titleKo: "1. 날짜",
    titleEn: "1. Dates",
    fields: [
      { id: "signYear", labelKo: "체결일 — 연도", labelEn: "Signing — year", kind: "year", tokens: ["r1"], default: "2026" },
      { id: "signMonth", labelKo: "체결일 — 월", labelEn: "Signing — month", kind: "number", tokens: ["r2"] },
      { id: "signDay", labelKo: "체결일 — 일", labelEn: "Signing — day", kind: "number", tokens: ["r3"] },
      { id: "paymentYear", labelKo: "납입기일 — 연도", labelEn: "Payment — year", kind: "year", tokens: ["r26"], default: "2026" },
      { id: "paymentMonth", labelKo: "납입기일 — 월", labelEn: "Payment — month", kind: "number", tokens: ["r27"] },
      { id: "paymentDay", labelKo: "납입기일 — 일", labelEn: "Payment — day", kind: "number", tokens: ["r28"] },
      { id: "financialsYear", labelKo: "재무제표 기준일 — 연도", labelEn: "Financials — year", kind: "year", tokens: ["r29"] },
      { id: "financialsMonth", labelKo: "재무제표 기준일 — 월", labelEn: "Financials — month", kind: "number", tokens: ["r30"] },
      { id: "financialsDay", labelKo: "재무제표 기준일 — 일", labelEn: "Financials — day", kind: "number", tokens: ["r31"] },
      {
        id: "closingYear",
        labelKo: "거래완결 기한 — 연도",
        labelEn: "Closing deadline — year",
        kind: "year",
        tokens: ["r33"],
        default: "2026",
        hintKo: "이 날까지 완결되지 않으면 해제 사유가 됩니다",
        hintEn: "Missing this date is grounds for termination",
      },
      { id: "closingMonth", labelKo: "거래완결 기한 — 월", labelEn: "Closing deadline — month", kind: "number", tokens: ["r34"] },
      { id: "closingDay", labelKo: "거래완결 기한 — 일", labelEn: "Closing deadline — day", kind: "number", tokens: ["r35"] },
    ],
  },
  {
    id: "rcps-parties",
    titleKo: "2. 당사자",
    titleEn: "2. Parties",
    fields: [
      {
        id: "investorName",
        labelKo: "투자자명",
        labelEn: "Investor name",
        kind: "text",
        tokens: ["r4"],
        default: "스파크랩 디스커버리펀드8호 개인투자조합",
        hintKo: "전문 · 서명란 · 별지2에 자동으로 채워집니다",
        hintEn: "Auto-filled in preamble, signature block, and Appendix 2",
      },
      { id: "investorAddress", labelKo: "투자자 주소", labelEn: "Investor address", kind: "text", tokens: ["r6"], hintKo: "전문 · 서명란에 자동으로 채워집니다", hintEn: "Auto-filled in preamble and signature block" },
      { id: "gpName", labelKo: "업무집행조합원", labelEn: "General partner", kind: "text", tokens: ["r7"], default: "주식회사 스파크랩" },
      { id: "gpRep", labelKo: "업무집행조합원 대표이사", labelEn: "GP representative", kind: "text", tokens: ["r8"], default: "김유진" },
      {
        id: "companyName",
        labelKo: "회사명",
        labelEn: "Company name",
        kind: "text",
        tokens: ["r5"],
        hintKo: "전문 · 서명란 · 별지2에 자동으로 채워집니다",
        hintEn: "Auto-filled in preamble, signature block, and Appendix 2",
      },
      { id: "companyAddress", labelKo: "회사 주소", labelEn: "Company address", kind: "text", tokens: ["r9"], hintKo: "전문 · 서명란에 자동으로 채워집니다", hintEn: "Auto-filled in preamble and signature block" },
      { id: "companyRep", labelKo: "회사 대표자", labelEn: "Company representative", kind: "text", tokens: ["r10"] },
      {
        id: "interestedName",
        labelKo: "이해관계인 성명",
        labelEn: "Interested party — name",
        kind: "text",
        tokens: ["r32", "r66"],
        hintKo: "전문 · 서명란 · 별지2에 자동으로 채워집니다",
        hintEn: "Auto-filled in preamble, signature block, and Appendix 2",
      },
      { id: "interestedAddress", labelKo: "이해관계인 주소", labelEn: "Interested party address", kind: "text", tokens: ["r11"], hintKo: "전문 · 서명란에 자동으로 채워집니다", hintEn: "Auto-filled in preamble and signature block" },
      { id: "interestedBirthYear", labelKo: "이해관계인 생년 (YYYY)", labelEn: "Interested party birth year", kind: "number", tokens: ["r12"] },
      { id: "interestedBirthMonth", labelKo: "이해관계인 생월", labelEn: "Interested party birth month", kind: "number", tokens: ["r13"] },
      { id: "interestedBirthDay", labelKo: "이해관계인 생일", labelEn: "Interested party birth day", kind: "number", tokens: ["r14"] },
    ],
  },
  {
    id: "rcps-terms",
    titleKo: "3. 투자 조건",
    titleEn: "3. Investment terms",
    fields: [
      { id: "newShares", labelKo: "본건 종류주식 수 (상환전환우선주)", labelEn: "New RCPS shares", kind: "number", tokens: ["r15"] },
      { id: "authShares", labelKo: "발행할 주식의 총수", labelEn: "Total authorised shares", kind: "number", tokens: ["r16"] },
      { id: "commonShares", labelKo: "기 발행 보통주 총수", labelEn: "Existing common shares", kind: "number", tokens: ["r17"] },
      { id: "existingPreferred", labelKo: "기 발행 상환전환우선주 수", labelEn: "Existing RCPS shares", kind: "number", tokens: ["r18"] },
      { id: "issueShares", labelKo: "본건 종류주식 종류와 수", labelEn: "Class and count issued", kind: "number", tokens: ["r19"] },
      { id: "parValue", labelKo: "1주당 액면가액 (숫자)", labelEn: "Par value (figures)", kind: "money", tokens: ["r20"] },
      { id: "parValueParen", labelKo: "1주당 액면가액 (괄호)", labelEn: "Par value (parenthesis)", kind: "money", tokens: ["r21"] },
      { id: "issuePrice", labelKo: "1주당 발행가액 (숫자)", labelEn: "Issue price (figures)", kind: "money", tokens: ["r22"] },
      { id: "issuePriceParen", labelKo: "1주당 발행가액 (괄호)", labelEn: "Issue price (parenthesis)", kind: "money", tokens: ["r23"] },
      { id: "totalAmount", labelKo: "총 인수대금 (숫자)", labelEn: "Total amount (figures)", kind: "money", tokens: ["r24"] },
      { id: "totalAmountParen", labelKo: "총 인수대금 (괄호)", labelEn: "Total amount (parenthesis)", kind: "money", tokens: ["r25"] },
      {
        id: "copies",
        labelKo: "계약서 부수",
        labelEn: "Number of copies",
        kind: "number",
        tokens: ["r36"],
        default: "3",
        hintKo: "기본 3부: 스파크랩·회사·대표자. 추가 이해관계인이 있으면 그만큼 늘립니다.",
        hintEn: "3 by default: SparkLabs, company, representative. Add one per extra interested party.",
      },
    ],
  },
  {
    id: "rcps-notices",
    titleKo: "4. 통지 수신처",
    titleEn: "4. Notices",
    fields: [
      { id: "noticeInvestorTo", labelKo: "투자자 — 수신인", labelEn: "Investor — recipient", kind: "text", tokens: ["r37"] },
      {
        id: "noticeInvestorAddress",
        labelKo: "투자자 — 주소",
        labelEn: "Investor — address",
        kind: "text",
        tokens: ["r38"],
        default: "서울특별시 강남구 역삼로180, 3층(역삼동, 마루180)",
      },
      { id: "noticeInvestorEmail", labelKo: "투자자 — 이메일", labelEn: "Investor — email", kind: "text", tokens: ["r39"] },
      { id: "noticeCompanyTo", labelKo: "회사 — 수신인", labelEn: "Company — recipient", kind: "text", tokens: ["r40"] },
      { id: "noticeCompanyAddress", labelKo: "회사 — 주소", labelEn: "Company — address", kind: "text", tokens: ["r41"] },
      { id: "noticeCompanyPhone", labelKo: "회사 — 전화", labelEn: "Company — phone", kind: "text", tokens: ["r42"] },
      { id: "noticeCompanyEmail", labelKo: "회사 — 이메일", labelEn: "Company — email", kind: "text", tokens: ["r43"] },
      { id: "noticeInterestedTo", labelKo: "이해관계인 — 수신인", labelEn: "Interested party — recipient", kind: "text", tokens: ["r44"] },
      { id: "noticeInterestedAddress", labelKo: "이해관계인 — 주소", labelEn: "Interested party — address", kind: "text", tokens: ["r45"] },
      { id: "noticeInterestedPhone", labelKo: "이해관계인 — 전화", labelEn: "Interested party — phone", kind: "text", tokens: ["r46"] },
      { id: "noticeInterestedEmail", labelKo: "이해관계인 — 이메일", labelEn: "Interested party — email", kind: "text", tokens: ["r47"] },
    ],
  },
  {
    id: "rcps-standard",
    titleKo: "5. 표준 조항",
    titleEn: "5. Standard terms",
    fields: [
      {
        id: "dividendRate",
        labelKo: "우선배당률 (%)",
        labelEn: "Preferred dividend rate (%)",
        kind: "percent",
        tokens: ["r48"],
        default: "1",
        standard: true,
        hintKo: "스파크랩 표준 연 1%",
        hintEn: "SparkLabs standard is 1% p.a.",
      },
      {
        id: "lateDividendRate",
        labelKo: "배당금 지연배상 이율 (%)",
        labelEn: "Late dividend interest (%)",
        kind: "percent",
        tokens: ["r49"],
        default: "12",
        standard: true,
        hintKo: "스파크랩 표준 연복리 12% (배당금 연체 가산금)",
        hintEn: "SparkLabs standard is 12% p.a. compound (late dividend surcharge)",
      },
      {
        id: "liquidationRate",
        labelKo: "잔여재산 분배 이율 (%)",
        labelEn: "Liquidation preference rate (%)",
        kind: "percent",
        tokens: ["r50"],
        default: "7",
        standard: true,
        hintKo: "스파크랩 표준 연복리 7% (잔여재산 분배 우선)",
        hintEn: "SparkLabs standard is 7% p.a. compound (liquidation preference)",
      },
      {
        id: "ipoConversionPct",
        labelKo: "IPO 전환비율 조정 기준 (%)",
        labelEn: "IPO conversion adjustment (%)",
        kind: "percent",
        tokens: ["r51", "r52"],
        default: "70",
        standard: true,
        hintKo: "스파크랩 표준 70% — IPO 전환 조항 2곳에 동시 반영",
        hintEn: "SparkLabs standard is 70% — fills both IPO conversion clauses",
      },
      {
        id: "maConversionPct",
        labelKo: "M&A 전환가액 조정 기준 (%)",
        labelEn: "M&A conversion adjustment (%)",
        kind: "percent",
        tokens: ["r53", "r54"],
        default: "70",
        standard: true,
        hintKo: "스파크랩 표준 70% — M&A 전환 조항 2곳에 동시 반영",
        hintEn: "SparkLabs standard is 70% — fills both M&A conversion clauses",
      },
      {
        id: "redemptionStartYears",
        labelKo: "상환청구 가능 시점 (납입 후 년)",
        labelEn: "Redemption start (years after payment)",
        kind: "number",
        tokens: ["r55"],
        default: "2",
        standard: true,
        hintKo: "스파크랩 표준 2년 — '납입기일로부터 2년이 경과한 날부터 상환 청구 가능'",
        hintEn: "SparkLabs standard is 2 years after payment date",
      },
      {
        id: "redemptionInterest",
        labelKo: "상환금 산정 이율 (%)",
        labelEn: "Redemption amount interest (%)",
        kind: "percent",
        tokens: ["r56"],
        default: "7",
        standard: true,
        hintKo: "스파크랩 표준 연복리 7% (상환금 계산식)",
        hintEn: "SparkLabs standard is 7% p.a. compound (redemption formula)",
      },
      {
        id: "earlyRedemptionInterest",
        labelKo: "조기상환 이율 (%)",
        labelEn: "Early redemption interest (%)",
        kind: "percent",
        tokens: ["r57"],
        default: "12",
        standard: true,
        hintKo: "스파크랩 표준 연복리 12% (조기상환 조항)",
        hintEn: "SparkLabs standard is 12% p.a. compound (early redemption clause)",
      },
      {
        id: "buybackInterest",
        labelKo: "주식매수 시 연복리 (%)",
        labelEn: "Buyback compound interest (%)",
        kind: "percent",
        tokens: ["r58"],
        default: "15",
        standard: true,
        hintKo: "스파크랩 표준 연복리 15% (주식매수청구 단가 산정)",
        hintEn: "SparkLabs standard is 15% p.a. compound (buyback price formula)",
      },
      {
        id: "buybackLookbackYears",
        labelKo: "주식매수 단가 산정 기간 (년)",
        labelEn: "Buyback price lookback (years)",
        kind: "number",
        tokens: ["r59"],
        default: "1",
        hintKo: "과거 이 기간의 최고 매매단가를 참고하여 매수가를 산정",
        hintEn: "Buyback price is compared against highest trade price over this lookback",
      },
      {
        id: "penaltyRate",
        labelKo: "위약벌 비율 (%)",
        labelEn: "Liquidated damages rate (%)",
        kind: "percent",
        tokens: ["r60"],
        default: "12",
        standard: true,
        hintKo: "스파크랩 표준 12% — '총 주식인수대금의 12%를 위약벌로'",
        hintEn: "SparkLabs standard is 12% of total subscription amount",
      },
      {
        id: "lockupYears",
        labelKo: "퇴사제한 기간 (년)",
        labelEn: "Employment lock-up (years)",
        kind: "number",
        tokens: ["r61"],
        default: "4",
        standard: true,
        hintKo: "스파크랩 표준 4년 (별지2 퇴사제한 조항)",
        hintEn: "SparkLabs standard is 4 years (Appendix 2 lock-up clause)",
      },
      {
        id: "noncompeteYears",
        labelKo: "경업금지 기간 (년)",
        labelEn: "Non-compete period (years)",
        kind: "number",
        tokens: ["r62", "r63"],
        default: "2",
        standard: true,
        hintKo: "스파크랩 표준 2년 — 별지2 경업금지 조항 2곳에 동시 반영",
        hintEn: "SparkLabs standard is 2 years — fills both non-compete clauses in Appendix 2",
      },
      {
        id: "ipoLockupYears",
        labelKo: "상장 후 퇴사제한 해제 (년)",
        labelEn: "Lock-up lifted after listing (years)",
        kind: "number",
        tokens: ["r64", "r65"],
        default: "1",
        hintKo: "IPO 후 이 기간이 경과하면 퇴사제한 해제 — 별지2 두 곳",
        hintEn: "Lock-up ends this many years after IPO — fills two clauses in Appendix 2",
      },
      {
        id: "redemptionDays",
        labelKo: "상환 지급기한 (일)",
        labelEn: "Redemption payment window (days)",
        kind: "number",
        tokens: ["r67"],
        default: "60",
        standard: true,
        hintKo: "스파크랩 표준 60일 — '상환 요구일로부터 N일 이내 지급'",
        hintEn: "SparkLabs standard is 60 days from redemption request",
      },
      {
        id: "capitalReserveRatio",
        labelKo: "자본준비금 한도 배율",
        labelEn: "Capital reserve ratio",
        kind: "number",
        tokens: ["r68"],
        default: "1.5",
        standard: true,
        hintKo: "스파크랩 표준 1.5배 — 자본준비금·이익준비금 합계가 납입자본금의 N배 초과 시 현금배당 가능",
        hintEn: "SparkLabs standard is 1.5× paid-in capital; fills both occurrences",
      },
      {
        id: "latePaymentRate",
        labelKo: "금전지급 지연이자율 (%)",
        labelEn: "Late payment interest rate (%)",
        kind: "percent",
        tokens: ["r69"],
        default: "12",
        standard: true,
        hintKo: "스파크랩 표준 연 12% — 계약상 금전지급의무 연체 시 가산이율",
        hintEn: "SparkLabs standard is 12% p.a. — applies to any overdue contractual payment",
      },
    ],
  },
];
